name: Commitlint # Define the name of the workflow

on: [push, pull_request] # Trigger the workflow on push and pull request events

jobs:                                   # Initialise job
  lint:                                 # Define a job named 'lint'
    runs-on: ubuntu-latest              # Specifies the type of VM to provision

    container:                          # Set container image
      image: monkeyknuckles/commitlint  # Points to Commitlint container

    steps:                              # List of steps to execute
      - name: Checkout code             # Checkout code label text
        uses: actions/checkout@v3       # Use the checkout action to clone the repository
        with:
          fetch-depth: 0                # Fetch all history for linting purposes

      - name: Configure Git safe directory                              # Add workspace to safe directory list label
        run: git config --global --add safe.directory $GITHUB_WORKSPACE # Add workspace to safe directory list label
      
      - name: Copy Commitlint config                    # Copy Commitlint configuration file label text
        run: cp /app/.commitlint.yaml $GITHUB_WORKSPACE # Include the Commitlint configuration file in the docker build

      - name: Run Commitlint                            # Set lint Commitlint label text 
        run: commitlint -l -c -s -g .commitlint.yaml    # Lint comment
